version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: gps
      POSTGRES_USER: gps
      POSTGRES_DB: gps
    ports:
      - "5432:5432"
    volumes:
      - ./src/migrations/01_seed_db.sql:/docker-entrypoint-initdb.d/01_seed_db.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "50053:50053"
    depends_on:
      - db
    environment:
      DB_ADDRESS: db
      DB_USERNAME: gps
      DB_PASSWORD: gps
      DB_DATABASE: gps
      GRPC_SERVER_ADDRESS: 0.0.0.0:50053
      GRPC_SERVER_PORT: 9090
      NODE_ENV: "production"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
volumes:
  db-data:
